name: mytest_workflow
on: [push]
jobs:
    firstjob:
        runs-on: ubuntu-latest
        steps:
          - name: checkout repo
            uses: actions/checkout@v4
          - name: install cowsay
            run: sudo apt-get install -y cowsay
    secondjob:
      needs: firstjob
      runs-on: ubuntu-latest
      steps:
        - name: echo cowsay
          run: cowsay -f beefymiracle Hello Actions!!

            
